version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8082:8080
      - 50000:50000
    container_name: jenkins-lts
    volumes:
      - ~/GIT/cursoqa/jenkins/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker

  agent:
    image: jenkins/ssh-agent:jdk11
    privileged: true
    user: root
    container_name: agent
    expose:
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC3tgkWHZf7cqZt77C3YdVPeej1k5cj5MDBc9GzngW6O2j2nytijuVPjqt5Dyw3VxNZjXKV/5dSLf2B1Ug5799hsQv8zviNjuQai7UfIwWCDGS7K3uhAJUsbXI8DbkFqIx/XM1yHOd571AecEoCaOj4HETEqaF9C7iZUzyVuG881fQGpyer66jX6NCsTKc9rT90+V39NWwsna3M8NlF/ZRByJeonSYdMSHDsa4Dyd0DN8ByjGiqHR+7DVN92yk79VFnnNuiAAbq5uk68CeAMxB0rUwXl20K2jqc6uQEQYA9RFrzHG6Xqyx1pgeehXLbMG+EePHaZ83jni9xzeLkRIt7jRTIUecxq7TqUmLkDR3WCa6+4aIR/qUWMrePea3sgh1ZJatquBcqqOBOTxYoBf1mnVK+zPk1tk1RURaa4KTA1sYVWMIXw2TvyQ+j3DI5axH485Odz8cUPyFUX6eIMq56GtnmA7rIFJNG/J8LfWrxJi5a/lY2Rl/tXttYowFApv8= tav@archlinux